server:
  port: 8088
spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contacts_group
    username: root
    password: 1234
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 100KB
      max-request-size: 3MB # 30 张图片，每张 100KB 总共 3MB
      enabled: true
  #静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 设置 MyBatis 使用 stdout 输出日志
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
  mapper-locations: classpath:mapper/*.xml   # 指定 MyBatis XML 映射文件的位置，classpath 前面不需要加 *:

